"""Strip AI co-author trailers from commit messages (stdin -> stdout)."""
import sys

skip_prefixes = (
    'Co-Authored-By:',
    'Co-authored-by:',
    'co-authored-by:',
    'Generated-by:',
    'Generated by Cursor',
    'Generated with Claude',
)

lines = sys.stdin.read().splitlines(True)
out = []
for line in lines:
    if any(line.startswith(p) or p in line for p in skip_prefixes if p.endswith(':')):
        if line.lstrip().startswith(tuple(p for p in skip_prefixes if p.endswith(':'))):
            continue
    if line.strip().startswith('Co-Authored-By:') or line.strip().startswith('Co-authored-by:'):
        continue
    if 'noreply@anthropic.com' in line or 'cursoragent' in line.lower():
        continue
    out.append(line)

# trim trailing blank lines left by removed trailer
while out and out[-1].strip() == '':
    out.pop()
if out and not out[-1].endswith('\n'):
    out[-1] += '\n'
elif out:
    pass
else:
    out = ['\n']

sys.stdout.write(''.join(out))
if out and not ''.join(out).endswith('\n'):
    sys.stdout.write('\n')
